version: '3'

services:
  app:
    build:
      context: node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: node index.js
    volumes:
      - ./node:/usr/src/app
      - '/usr/src/app/node_modules'
    tty: true
    networks:
      - node-network
    depends_on:
      - db

  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

  nginx:
    build:
      context: nginx
    container_name: nginx
    tty: true
    ports:
      - '8080:80'
    networks:
      - node-network
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
